# Generated by Django 4.2.5 on 2023-09-21 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_agentvanzari_managerdepozit_manipulatordepozit'),
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='manipulator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manipulator', to='Users.manipulatordepozit'),
            preserve_default=False,
        ),
    ]
