# Generated by Django 4.2.5 on 2023-09-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_agentvanzari_managerdepozit_manipulatordepozit'),
        ('Task', '0002_task_manipulator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Agent', to='Users.agentvanzari'),
        ),
    ]
