# Generated by Django 4.2.5 on 2023-09-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_alter_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='confirmare_manipulare',
            field=models.CharField(blank=True, choices=[('ALONE', 'Incep comanda si ma descurc singur'), ('NOT ALONE', 'Incep comanda si am nevoie de ajutor')], max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='extra_observatii',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='numar_colete',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='observatii_factura',
            field=models.CharField(choices=[('STORNARE', 'Contine produse stornate'), ('FARA OBSERVATII', 'Nici o observatie'), ('OTHER', 'Alte Observatii')], default='FARA OBSERVATII', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='status_ambalare',
            field=models.CharField(default='Produsele sunt ambalate si depozitate', max_length=250),
        ),
        migrations.AddField(
            model_name='task',
            name='status_pregatire_produse',
            field=models.CharField(choices=[('PRODUSE VERIFICATE - FARA PROBLEME', 'Toate produsele sunt verificate - nu prezinta probleme'), ('PRODUSE VERIFICATE - PROBLEME MICI', 'Toate produsele sunt verificate - dar exista probleme mici'), ('PRODUSE VERIFICATE - PROBLEME MARI', 'Toate produsele sunt verificate - dar exista probleme mari'), ('PROBLEME IDENTIFICARE', 'Am probleme la identificarea produselor'), ('PROBLEME CALITATE', 'Am probleme cu calitatea produselor')], default='PRODUSE VERIFICATE - FARA PROBLEME', max_length=250),
        ),
        migrations.AddField(
            model_name='task',
            name='status_preluare',
            field=models.CharField(blank=True, choices=[('CURIER', 'Preluata Curier'), ('TRANSPORT SPECIAL', 'Preluata transport special'), ('TRANSPORT ARN', 'Preluata transport ARN'), ('RECEPTIE CLIENT', 'Receptie client')], max_length=150),
        ),
        migrations.AddField(
            model_name='task',
            name='volum_comanda',
            field=models.CharField(blank=True, choices=[('FOARTE MIC', ' Foarte mic'), ('MIC', 'Mic'), ('MEDIU', 'Mediu'), ('MARE', 'Mare'), ('PACHETE MARI', 'Contine pachete mari')], max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='curier',
            field=models.CharField(blank=True, choices=[('DRAGON STAR', 'Dragon Star'), ('PPT', 'PPT'), ('DPD', 'DPD'), ('DIMENSIUNI NECESARE', 'Dimensiuni necesare')], max_length=250),
        ),
    ]
