# Generated by Django 4.2.5 on 2023-09-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_agentvanzari_managerdepozit_manipulatordepozit'),
        ('Task', '0004_task_confirmare_manipulare_task_extra_observatii_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='manipulator',
        ),
        migrations.AddField(
            model_name='task',
            name='manipulator',
            field=models.ManyToManyField(to='Users.manipulatordepozit'),
        ),
    ]
